### ISSUE TITLE
4.0+spring版本的报错

### ISSUE THREAD

**Issue by Stevenhuangqian** [selfly/dexcoder-assistant#1]
我项目使用的是最新的spring版本，queryCount里面使用到的jdbcTemplate的queryForInt方法已经在spring底层去除了，编译的时候没问题，到实际运行就会出现nosuchmethod的异常。。希望作者能够增加对spring4的支持，把底层改为queryForObject实现。

**Comment by selfly** [comment]
这个早就支持了啊

**Comment by Stevenhuangqian** [comment]
已经看到最新版感谢作者
