### ISSUE TITLE
criteria查询方式时同一个字段存在多个限制条件时只有一个生效

### ISSUE THREAD

**Issue by lanluobo** [selfly/dexcoder-assistant#2]
您好:
       目前遇到一个问题,就是使用criteria方式查询时,比如我要查询time在'2016-04-10'和'2016-04-15'之间的数据,如果如下写法:
   criteria.and("deployTime", ">", new Object[]{  '2016-04-10' });
   criteria.and("deployTime", "<", new Object[]{  '2016-04-15' });
最终得到的数据却是 时间小于 '2016-04-15' 的数据,第一个条件 时间大于'2016-04-10'失效了.而如果我单独使用大于或是小于的时间来查询都能得到正确的数据,但是2个条件一起查询却只有后一个条件生效.

**Comment by selfly** [comment]
你好，确实存在这个问题，目前已经修正，git上源码已经提交，不久后会推送到Maven中央库。
非常感谢！

**Comment by lanluobo** [comment]
已确认最新包..很给力~~感谢作者的快速修正~~
