### ISSUE TITLE
batis like应该怎么写

### ISSUE THREAD

**Issue by foolishchow** [selfly/dexcoder-assistant#4]
`<where>
            1=1 and t.has_purchase in ('0','1')
            <if test="parameters != null and parameters.buyerName != null and parameters.buyerName != ''">
                t.buyer_name like concat('%',${parameters.buyerName},'%')
            </if>
        </where>`
like 应该怎么写

**Comment by selfly** [comment]
like "%"#{parameters.buyerName}"%"
