### ISSUE TITLE
希望能够开放表名与字段名强制大写转换的配置出来

### ISSUE THREAD

**Issue by folochina** [selfly/dexcoder-assistant#5]
希望能够开放表名与字段名强制大写转换的配置出来

**Comment by selfly** [comment]
数据库对这个大小写应该不敏感吧，目前都是大写

**Comment by lanluobo** [comment]
不是啊,至少Linux上mysql默认表名大小写是敏感的..虽然可以通过改数据库配置文件使其不敏感,但是需要重启数据库,这个是否在程序级别可控一点会更好呢?
